---
title: "Test an additional maize line and soil origin"
author: "Valentin Gfeller"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#global knitter option
knitr::opts_chunk$set(fig.align = "center", dev = 'svglite', echo = FALSE)

#Load packages
library(tidyverse); packageVersion("tidyverse")
library(emmeans); packageVersion("emmeans")
library(nlme); packageVersion("nlme")
library(car); packageVersion("car")
library(here); packageVersion("here")
library(ggbeeswarm); packageVersion("ggbeeswarm")
library(knitr); packageVersion("knitr")
library(ggtext); packageVersion("ggtext")
library(cowplot); packageVersion("cowplot")
library(ggprism); packageVersion("ggprism")

# set global ggplot2 options
theme_set(theme_bw(base_size = 11))

# load handy functions
source(here("Scripts", "functions.R"))
```



```{r, warning=F, echo=F, message=F, include=F}
# load data
d.precrop <- read_delim(here("Data", "Phen_precr_lin_soil.csv"),
                        delim = ",", col_names = TRUE) %>%
  mutate(precrop = factor(precrop, levels = c("Tri", "Med")))

str(d.precrop)
```

```{r include=FALSE}
# set graphical appearance of plots
x_labs <- c("Tri" = "T. aestivum",
            "Med" = "M. sativa")

fill_values <- c(w = "darkgoldenrod1", 
                 b = "darkolivegreen4")
fill_labels <- c(w = "WT", 
                 b = expression(italic("bx1")))

facet_labels <- as_labeller(c(changins = "Changins", q_matte = "Q-matte"))

```

## Dry weight - Fig.S3a
```{r}
tab.t.test_c <- d.precrop %>%
  filter(soil == "changins") %>% 
  t.test(dw_precrop ~ precrop, data = .) %>%
  broom::glance(.) %>%
  mutate(p_print = case_when(p.value < 0.001 ~ as.character("p < 0.001"),
                             TRUE  ~ paste0("p = ", sprintf("%.3f", p.value))),
         x = 1.5,
         y = Inf,
         soil = "changins") %>% 
  select(p_print, x, y, soil)


tab.t.test_q <- d.precrop %>%
  filter(soil == "q_matte") %>% 
  t.test(dw_precrop ~ precrop, data = .) %>%
  broom::glance(.) %>%
  mutate(p_print = case_when(p.value < 0.001 ~ as.character("p < 0.001"),
                             TRUE  ~ paste0("p = ", sprintf("%.3f", p.value))),
         x = 1.5,
         y = Inf,
         soil = "q_matte") %>% 
  select(p_print, x, y, soil)

tab.t.test <- bind_rows(tab.t.test_c, tab.t.test_q)

p.pre <- d.precrop  %>%
      ggplot(aes(x = precrop, y = dw_precrop)) + 
      geom_boxplot(color = "darkgray", fill = "grey", outlier.colour = NA,
                   alpha = 0.3) +
      geom_quasirandom(data = d.precrop,
                       aes(x = precrop, y = dw_precrop), 
                       size = 2, shape = 21, width = 0.15, 
                       show.legend = FALSE, alpha = 0.8) +
      stat_summary(fun = mean, geom = "point", shape = 18, size = 3) +
      stat_summary(fun.data = mean_se, geom = "errorbar", linewidth = 1, 
               color = "black", width = 0.4) +
      xlab("Species") + 
      ylab("Dry weight (g)") +
      scale_y_continuous(breaks = c(seq(0, 14, by = 2)), 
                     expand = expansion(mult = c(0.1, 0.1))) +
      scale_x_discrete(labels = x_labs) +
      theme(axis.text.x = element_text(face = "italic"),
            plot.margin = margin(t = 3, r = 3, b = 3, l = 3, unit = "pt")) + 
  geom_text(data = tab.t.test,
            mapping = aes(x = x, y = y, label = p_print, fill = NULL),
            vjust = 2.5, size = 4) +
  facet_wrap(vars(soil), labeller = facet_labels)+
  theme(strip.text = element_textbox(face = "bold"))

p.pre 

ggsave(p.pre, filename = here("Results", "Fig.S3aPhen_precr_lin_soil.svg"),  
       height = 11.5, width = 12, units = "cm")



d.precrop %>% 
  group_by(precrop, soil) %>% 
  summarise(
    Mean = mean(dw_precrop, na.rm = TRUE),
    n = sum(!is.na(dw_precrop)))
```


# Maize phenotypes
```{r include=FALSE}
# load data
d.maize <- read_delim(here("Data", "Phen_maize_lin_soil.csv"),
                        delim = ",", col_names = TRUE) %>%
  mutate(precrop = factor(precrop, levels = c("Tri", "Med")),
         trt = factor(trt, levels = c("w", "b")))

str(d.maize)

```


```{r include=FALSE}
# set graphical appearance of plots
x_labs <- c("Tri" = "T. aestivum",
            "Med" = "M. sativa")

fill_values <- c(w = "darkgoldenrod1", 
                 b = "darkolivegreen4")
fill_labels <- c(w = "WT", 
                 b = expression(italic("bx1")))

facet_labels <- as_labeller(c(changins = "Changins", q_matte = "Q-matte",
                              W22 = "W22", B73 = "B73"))

```

## Height 3 weeks - Fig.2a
```{r warning=FALSE, include=FALSE, out.width="100%"}
# Changins B73
d.maize_C_B73 <- d.maize %>% 
  filter(soil == "changins",
         maize_line == "B73") %>% 
  droplevels()

# statistics
 # lm --> anova
mod.hei <- lm(height_3weeks ~ trt * precrop, data = d.maize_C_B73)

Anova(mod.hei)
summary(mod.hei)
plot.mod.vg(mod.hei)

 # gls --> anova
d.maize_C_B73_red <- d.maize_C_B73 %>% drop_na(height_3weeks)

m.hei_null <-  gls(height_3weeks ~ trt * precrop, data = d.maize_C_B73_red)
m.hei.gls <-  gls(height_3weeks ~ trt * precrop, data = d.maize_C_B73_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.hei.gls, m.hei_null) # --> gls

plot(m.hei.gls)
qqnorm(m.hei.gls, abline = c(0,1))
Anova(m.hei.gls) 

# extract anova table
t.anova_C_B73 <- create_anova_table_pre(m.hei.gls)
lab_anova_C_B73 <- create_anova_label_pre(m.hei.gls)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$height_3weeks %>% max(na.rm = TRUE)
tab.emm_C_B73 <- emmeans(m.hei.gls, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_C_B73$soil %>% unique(),
            maize_line = d.maize_C_B73$maize_line %>% unique()) %>%  print()


# Changins W22
d.maize_C_W22 <- d.maize %>% 
  filter(soil == "changins",
         maize_line == "W22") %>% 
  droplevels()

# statistics
 # lm --> anova
mod.hei <- lm(height_3weeks ~ trt * precrop, data = d.maize_C_W22)

Anova(mod.hei)
summary(mod.hei)
plot.mod.vg(mod.hei)

 # gls --> anova
d.maize_C_W22_red <- d.maize_C_W22 %>% drop_na(height_3weeks)

m.hei_null <-  gls(height_3weeks ~ trt * precrop, data = d.maize_C_W22_red)
m.hei.gls <-  gls(height_3weeks ~ trt * precrop, data = d.maize_C_W22_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.hei.gls, m.hei_null) # --> lm

plot(m.hei.gls)
qqnorm(m.hei.gls, abline = c(0,1))
Anova(m.hei.gls) 

# extract anova table
t.anova_C_W22<- create_anova_table_pre(mod.hei)
lab_anova_C_W22 <- create_anova_label_pre(mod.hei)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$height_3weeks %>% max(na.rm = TRUE)
tab.emm_C_W22 <- emmeans(mod.hei, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_C_W22$soil %>% unique(),
            maize_line = d.maize_C_W22$maize_line %>% unique()) %>%  print()

# Q-matte W22

# q_matte W22
d.maize_Q_W22 <- d.maize %>% 
  filter(soil == "q_matte",
         maize_line == "W22") %>% 
  droplevels()

# statistics
 # lm --> anova
mod.hei <- lm(height_3weeks ~ trt * precrop, data = d.maize_Q_W22)

Anova(mod.hei)
summary(mod.hei)
plot.mod.vg(mod.hei)

 # gls --> anova
d.maize_Q_W22_red <- d.maize_Q_W22 %>% drop_na(height_3weeks)

m.hei_null <-  gls(height_3weeks ~ trt * precrop, data = d.maize_Q_W22_red)
m.hei.gls <-  gls(height_3weeks ~ trt * precrop, data = d.maize_Q_W22_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.hei.gls, m.hei_null) # --> lm

plot(m.hei.gls)
qqnorm(m.hei.gls, abline = c(0,1))
Anova(m.hei.gls) 

# extract anova table
t.anova_Q_W22 <- create_anova_table_pre(mod.hei)
lab_anova_Q_W22<- create_anova_label_pre(mod.hei)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$height_3weeks %>% max(na.rm = TRUE)
tab.emm_Q_W22 <- emmeans(mod.hei, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_Q_W22$soil %>% unique(),
            maize_line = d.maize_Q_W22$maize_line %>% unique()) %>%  print()



tab.emm <- bind_rows(tab.emm_C_B73, tab.emm_C_W22, tab.emm_Q_W22)

```


```{r warning=FALSE, include=FALSE, out.width="100%"}

p.hei <- d.maize %>% 
  ggplot_precrop3(x = precrop, y = height_3weeks, fill = trt,
                  tab.emm = tab.emm) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.05)))  +
  labs(x = "Precrop", y ="Maize height (cm)") +
  add_anova_tab_lin_soil(tab = lab_anova_C_B73, x = 0.5, y = 57,
                         soil = "changins", maize_line = "B73") +
  add_anova_tab_lin_soil(tab = lab_anova_C_W22, x = 0.5, y = 57,
                         soil = "changins", maize_line = "W22") +
  add_anova_tab_lin_soil(tab = lab_anova_Q_W22, x = 0.5, y = 57,
                         soil = "q_matte", maize_line = "W22") +
  ggtitle("Height after 3 weeks")

p.hei 

ggsave(p.hei, filename = here("Results", "Fig.2a_Phen_maize_3w_lin_soil.svg"),
       height = 12, width = 18.5, units = "cm")

d.maize %>% 
  group_by(precrop, soil, maize_line, trt) %>% 
  summarise(
    Mean = mean(height_3weeks, na.rm = TRUE),
    n = sum(!is.na(height_3weeks)))
```

```{r warning=FALSE}
p.hei
```

## Height 6 weeks - Fig.S3b
```{r warning=FALSE, include=FALSE, out.width="100%"}
# Changins B73

# statistics
 # lm --> anova
mod.hei <- lm(height_6weeks ~ trt * precrop, data = d.maize_C_B73)

Anova(mod.hei)
summary(mod.hei)
plot.mod.vg(mod.hei)

 # gls --> anova
d.maize_C_B73_red <- d.maize_C_B73 %>% drop_na(height_6weeks)

m.hei_null <-  gls(height_6weeks ~ trt * precrop, data = d.maize_C_B73_red)
m.hei.gls <-  gls(height_6weeks ~ trt * precrop, data = d.maize_C_B73_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.hei.gls, m.hei_null) # --> lm

plot(m.hei.gls)
qqnorm(m.hei.gls, abline = c(0,1))
Anova(m.hei.gls) 

# extract anova table
t.anova_C_B73 <- create_anova_table_pre(mod.hei)
lab_anova_C_B73 <- create_anova_label_pre(mod.hei)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$height_6weeks %>% max(na.rm = TRUE)
tab.emm_C_B73 <- emmeans(mod.hei, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_C_B73$soil %>% unique(),
            maize_line = d.maize_C_B73$maize_line %>% unique()) %>%  print()


# Changins W22

# statistics
 # lm --> anova
mod.hei <- lm(height_6weeks ~ trt * precrop, data = d.maize_C_W22)

Anova(mod.hei)
summary(mod.hei)
plot.mod.vg(mod.hei)

 # gls --> anova
d.maize_C_W22_red <- d.maize_C_W22 %>% drop_na(height_6weeks)

m.hei_null <-  gls(height_6weeks ~ trt * precrop, data = d.maize_C_W22_red)
m.hei.gls <-  gls(height_6weeks ~ trt * precrop, data = d.maize_C_W22_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.hei.gls, m.hei_null) # --> lm

plot(m.hei.gls)
qqnorm(m.hei.gls, abline = c(0,1))
Anova(m.hei.gls) 

# extract anova table
t.anova_C_W22<- create_anova_table_pre(mod.hei)
lab_anova_C_W22 <- create_anova_label_pre(mod.hei)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$height_6weeks %>% max(na.rm = TRUE)
tab.emm_C_W22 <- emmeans(mod.hei, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_C_W22$soil %>% unique(),
            maize_line = d.maize_C_W22$maize_line %>% unique()) %>%  print()

# Q-matte W22

# statistics
 # lm --> anova
mod.hei <- lm(height_6weeks ~ trt * precrop, data = d.maize_Q_W22)

Anova(mod.hei)
summary(mod.hei)
plot.mod.vg(mod.hei)

 # gls --> anova
d.maize_Q_W22_red <- d.maize_Q_W22 %>% drop_na(height_6weeks)

m.hei_null <-  gls(height_6weeks ~ trt * precrop, data = d.maize_Q_W22_red)
m.hei.gls <-  gls(height_6weeks ~ trt * precrop, data = d.maize_Q_W22_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.hei.gls, m.hei_null) # --> lm

plot(m.hei.gls)
qqnorm(m.hei.gls, abline = c(0,1))
Anova(m.hei.gls) 

# extract anova table
t.anova_Q_W22 <- create_anova_table_pre(mod.hei)
lab_anova_Q_W22<- create_anova_label_pre(mod.hei)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$height_6weeks %>% max(na.rm = TRUE)
tab.emm_Q_W22 <- emmeans(mod.hei, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_Q_W22$soil %>% unique(),
            maize_line = d.maize_Q_W22$maize_line %>% unique()) %>%  print()



tab.emm <- bind_rows(tab.emm_C_B73, tab.emm_C_W22, tab.emm_Q_W22)

```

```{r warning=FALSE, include=FALSE, out.width="100%"}
p.hei <- d.maize %>% 
  ggplot_precrop3(x = precrop, y = height_6weeks, fill = trt,
                  tab.emm = tab.emm) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.05)))  +
  labs(x = "Precrop", y ="Maize height (cm)") +
  add_anova_tab_lin_soil(tab = lab_anova_C_B73, x = 0.5, y = 105,
                         soil = "changins", maize_line = "B73") +
  add_anova_tab_lin_soil(tab = lab_anova_C_W22, x = 0.5, y = 105,
                         soil = "changins", maize_line = "W22") +
  add_anova_tab_lin_soil(tab = lab_anova_Q_W22, x = 0.5, y = 83,
                         soil = "q_matte", maize_line = "W22")

p.hei

ggsave(p.hei, filename = here("Results", "Fig.S3b_Phen_maize_6w_lin_soil.svg"),
       height = 11.5, width = 16, units = "cm")


d.maize %>% 
  group_by(precrop, soil, maize_line, trt) %>% 
  summarise(
    Mean = mean(height_6weeks, na.rm = TRUE),
    n = sum(!is.na(height_6weeks)))
```

```{r warning=FALSE}
p.hei
```


## Dry weight 6 weeks - Fig.2b
```{r warning=FALSE, include=FALSE, out.width="100%"}
# Changins B73

# statistics
 # lm --> anova
mod.dw <- lm(dw_6weeks ~ trt * precrop, data = d.maize_C_B73)

Anova(mod.dw)
summary(mod.dw)
plot.mod.vg(mod.dw)

 # gls --> anova
d.maize_C_B73_red <- d.maize_C_B73 %>% drop_na(dw_6weeks)

m.dw_null <-  gls(dw_6weeks ~ trt * precrop, data = d.maize_C_B73_red)
m.dw.gls <-  gls(dw_6weeks ~ trt * precrop, data = d.maize_C_B73_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.dw.gls, m.dw_null) # --> lm

plot(m.dw.gls)
qqnorm(m.dw.gls, abline = c(0,1))
Anova(m.dw.gls) 

# extract anova table
t.anova_C_B73 <- create_anova_table_pre(mod.dw)
lab_anova_C_B73 <- create_anova_label_pre(mod.dw)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$dw_6weeks %>% max(na.rm = TRUE)
tab.emm_C_B73 <- emmeans(mod.dw, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_C_B73$soil %>% unique(),
            maize_line = d.maize_C_B73$maize_line %>% unique()) %>%  print()


# Changins W22

# statistics
 # lm --> anova
mod.dw <- lm(dw_6weeks ~ trt * precrop, data = d.maize_C_W22)

Anova(mod.dw)
summary(mod.dw)
plot.mod.vg(mod.dw)

 # gls --> anova
d.maize_C_W22_red <- d.maize_C_W22 %>% drop_na(dw_6weeks)

m.dw_null <-  gls(dw_6weeks ~ trt * precrop, data = d.maize_C_W22_red)
m.dw.gls <-  gls(dw_6weeks ~ trt * precrop, data = d.maize_C_W22_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.dw.gls, m.dw_null) # --> gls

plot(m.dw.gls)
qqnorm(m.dw.gls, abline = c(0,1))
Anova(m.dw.gls) 

# extract anova table
t.anova_C_W22<- create_anova_table_pre(m.dw.gls)
lab_anova_C_W22 <- create_anova_label_pre(m.dw.gls)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$dw_6weeks %>% max(na.rm = TRUE)
tab.emm_C_W22 <- emmeans(m.dw.gls, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_C_W22$soil %>% unique(),
            maize_line = d.maize_C_W22$maize_line %>% unique()) %>%  print()

# Q-matte W22

# statistics
 # lm --> anova
mod.dw <- lm(dw_6weeks ~ trt * precrop, data = d.maize_Q_W22)

Anova(mod.dw)
summary(mod.dw)
plot.mod.vg(mod.dw)

 # gls --> anova
d.maize_Q_W22_red <- d.maize_Q_W22 %>% drop_na(dw_6weeks)

m.dw_null <-  gls(dw_6weeks ~ trt * precrop, data = d.maize_Q_W22_red)
m.dw.gls <-  gls(dw_6weeks ~ trt * precrop, data = d.maize_Q_W22_red,
                 weights = varIdent(form = ~ 1 | trt * precrop))
anova(m.dw.gls, m.dw_null) # --> lm

plot(m.dw.gls)
qqnorm(m.dw.gls, abline = c(0,1))
Anova(m.dw.gls) 

# extract anova table
t.anova_Q_W22 <- create_anova_table_pre(mod.dw)
lab_anova_Q_W22<- create_anova_label_pre(mod.dw)

 # test maize_line effect for each precrop species (emmeans)
plot_max <- d.maize$dw_6weeks %>% max(na.rm = TRUE)
tab.emm_Q_W22 <- emmeans(mod.dw, specs = pairwise ~ trt | c(precrop)) %>% 
  .$contrasts %>%
     rbind(adjust = "fdr") %>% 
     summary(infer = TRUE) %>% tibble() %>% 
     mutate(max.y = plot_max * 1.02,
            trt = NA,
            soil = d.maize_Q_W22$soil %>% unique(),
            maize_line = d.maize_Q_W22$maize_line %>% unique()) %>%  print()



tab.emm <- bind_rows(tab.emm_C_B73, tab.emm_C_W22, tab.emm_Q_W22)

```

```{r warning=FALSE, include=FALSE, out.width="100%"}
p.dw <- d.maize %>% 
  ggplot_precrop3(x = precrop, y = dw_6weeks, fill = trt,
                  tab.emm = tab.emm) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.05)))  +
  labs(x = "Precrop", y ="Maize dry weight (g)") +
  add_anova_tab_lin_soil(tab = lab_anova_C_B73, x = 0.5, y = 13.3,
                         soil = "changins", maize_line = "B73") +
  add_anova_tab_lin_soil(tab = lab_anova_C_W22, x = 0.5, y = 13.3,
                         soil = "changins", maize_line = "W22") +
  add_anova_tab_lin_soil(tab = lab_anova_Q_W22, x = 0.5, y = 7.75,
                         soil = "q_matte", maize_line = "W22") +
  # theme(legend.position = "top")+
  ggtitle("Maize dry weight after 6 weeks")

p.dw

ggsave(p.dw, filename = here("Results", "Fig.2b_Phen_maize_dw_6w_lin_soil.svg"),
       height = 12, width = 18.5, units = "cm")



d.maize %>% 
  group_by(precrop, soil, maize_line, trt) %>% 
  summarise(
    Mean = mean(dw_6weeks, na.rm = TRUE),
    n = sum(!is.na(dw_6weeks)))
```

```{r warning=FALSE}
p.dw
```
